### PR TITLE
Fix local

### PR DESCRIPTION
**Pull request by iandyh**

### CODE REVIEW

**Comment by iandyh** [comment]
This should work on an ARM mac with Resetta simulation on Lima.

**Comment by rsw-a** [comment]
@iandyh 
when i run make command at my local. i encountered the error as follows. it's because netskope thing. you can refer to this [link](https://rakutenghd.zendesk.com/hc/en-us/articles/14622819893913--Netskope-Workarounds-for-SSL-TLS-certificate-errors#h_01GQ1ZCJ1KP1VPY1915888ECE4).  can you take this into account for local docker image build.
```
...
cd shibuya && sh build.sh api
docker build -f shibuya/Dockerfile --build-arg env=local -t api:local shibuya
[+] Building 46.1s (8/10)                                                                                                                                                                                                                           docker:orbstack
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                           0.0s
 => => transferring dockerfile: 577B                                                                                                                                                                                                                           0.0s
 => [internal] load metadata for docker.io/library/ubuntu:18.04                                                                                                                                                                                                1.6s
 => [auth] library/ubuntu:pull token for registry-1.docker.io                                                                                                                                                                                                  0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                              0.0s
 => => transferring context: 2B                                                                                                                                                                                                                                0.0s
 => CACHED [1/5] FROM docker.io/library/ubuntu:18.04@sha256:152dc042452c496007f07ca9127571cb9c29697f42acbfad72324b2bb2e43c98                                                                                                                                   0.0s
 => [internal] load build context                                                                                                                                                                                                                              0.2s
 => => transferring context: 35.98MB                                                                                                                                                                                                                           0.2s
 => [2/5] RUN apt-get update && apt-get install -y curl                                                                                                                                                                                                       44.2s
 => ERROR [3/5] RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl     && chmod +x ./kubectl     && mv ./kubectl /usr/local/bin/k  0.3s
------                                                                                                                                                                                                                                                              
 > [3/5] RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl     && chmod +x ./kubectl     && mv ./kubectl /usr/local/bin/kubectl:       
0.190   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                                                                                                                                               
0.190                                  Dload  Upload   Total   Spent    Left  Speed                                                                                                                                                                                 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0                                                                                                                                                                                      
0.312 curl: (60) SSL certificate problem: self signed certificate in certificate chain
0.312 More details here: https://curl.haxx.se/docs/sslcerts.html
0.312 
0.312 curl failed to verify the legitimacy of the server and therefore could not
0.312 establish a secure connection to it. To learn more about this situation and
0.312 how to fix it, please visit the web page mentioned above.
------
Dockerfile:4
--------------------
   3 |     RUN apt-get update && apt-get install -y curl
   4 | >>> RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl \
   5 | >>>     && chmod +x ./kubectl \
   6 | >>>     && mv ./kubectl /usr/local/bin/kubectl
   7 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl     && chmod +x ./kubectl     && mv ./kubectl /usr/local/bin/kubectl" did not complete successfully: exit code: 60
make: *** [local_api] Error 1
```

**Comment by rsw-a** [comment]
one more thing, [db.yaml](https://github.com/iandyh/shibuya/blob/09defe666d0f914a90b6c8b54279ab7bc30d8596/kubernetes/db.yaml) has still pretty old mariadb image v10.0.23. we should at least update to v10.0.36 because old ver doesn't support arm64 arch.

**Comment by iandyh** [comment]
> @iandyh when i run make command at my local. i encountered the error as follows. it's because netskope thing. you can refer to this [link](https://rakutenghd.zendesk.com/hc/en-us/articles/14622819893913--Netskope-Workarounds-for-SSL-TLS-certificate-errors#h_01GQ1ZCJ1KP1VPY1915888ECE4). can you take this into account for local docker image build.
> 
> ```
> ...
> cd shibuya && sh build.sh api
> docker build -f shibuya/Dockerfile --build-arg env=local -t api:local shibuya
> [+] Building 46.1s (8/10)                                                                                                                                                                                                                           docker:orbstack
>  => [internal] load build definition from Dockerfile                                                                                                                                                                                                           0.0s
>  => => transferring dockerfile: 577B                                                                                                                                                                                                                           0.0s
>  => [internal] load metadata for docker.io/library/ubuntu:18.04                                                                                                                                                                                                1.6s
>  => [auth] library/ubuntu:pull token for registry-1.docker.io                                                                                                                                                                                                  0.0s
>  => [internal] load .dockerignore                                                                                                                                                                                                                              0.0s
>  => => transferring context: 2B                                                                                                                                                                                                                                0.0s
>  => CACHED [1/5] FROM docker.io/library/ubuntu:18.04@sha256:152dc042452c496007f07ca9127571cb9c29697f42acbfad72324b2bb2e43c98                                                                                                                                   0.0s
>  => [internal] load build context                                                                                                                                                                                                                              0.2s
>  => => transferring context: 35.98MB                                                                                                                                                                                                                           0.2s
>  => [2/5] RUN apt-get update && apt-get install -y curl                                                                                                                                                                                                       44.2s
>  => ERROR [3/5] RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl     && chmod +x ./kubectl     && mv ./kubectl /usr/local/bin/k  0.3s
> ------                                                                                                                                                                                                                                                              
>  > [3/5] RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl     && chmod +x ./kubectl     && mv ./kubectl /usr/local/bin/kubectl:       
> 0.190   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                                                                                                                                               
> 0.190                                  Dload  Upload   Total   Spent    Left  Speed                                                                                                                                                                                 
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0                                                                                                                                                                                      
> 0.312 curl: (60) SSL certificate problem: self signed certificate in certificate chain
> 0.312 More details here: https://curl.haxx.se/docs/sslcerts.html
> 0.312 
> 0.312 curl failed to verify the legitimacy of the server and therefore could not
> 0.312 establish a secure connection to it. To learn more about this situation and
> 0.312 how to fix it, please visit the web page mentioned above.
> ------
> Dockerfile:4
> --------------------
>    3 |     RUN apt-get update && apt-get install -y curl
>    4 | >>> RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl \
>    5 | >>>     && chmod +x ./kubectl \
>    6 | >>>     && mv ./kubectl /usr/local/bin/kubectl
>    7 |     
> --------------------
> ERROR: failed to solve: process "/bin/sh -c curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl     && chmod +x ./kubectl     && mv ./kubectl /usr/local/bin/kubectl" did not complete successfully: exit code: 60
> make: *** [local_api] Error 1
> ```

maybe we can add the comment. But I think I'll exclude the logic in the script because this is unique to us.

> several things, [db.yaml](https://github.com/iandyh/shibuya/blob/09defe666d0f914a90b6c8b54279ab7bc30d8596/kubernetes/db.yaml) has still pretty old mariadb image v10.0.23. we should at least update to v10.0.36 because old ver doesn't support arm64 arch.
> 
> also, kubectl port-forward applies external-port:internal-port mapping to loopback address (127.0.0.1) as default. but it doesn't listen all incoming request from Host OS. we need to listen 8080 and 3000 port as '0.0.0.0' INADDR_ANY. so need to add up --address option in the kubectl port-forward command to expose directives at makefile. (this would be required when we run shibuya along with any VMs.)

Can you run db.yaml though? Somehow with colima, I can run it....Based on Colima docs, it seems it's possible: https://github.com/abiosoft/colima/discussions/631#discussioncomment-5107608

What docker deskstop solution you are using? I think we can upgrade the new version but one of the concern is I don't want DB to have big version gap with the one running in prod.

About port-forwarding, I don't fully get what you mean. After port-forward, you should be able to to go to `localhost:8080` to check the UI?

**Comment by rsw-a** [comment]
@iandyh 

> maybe we can add the comment. But I think I'll exclude the logic in the script because this is unique to us.
right. i forgot that shibuya is oss. 

as for  db.yaml stuff, I've run the shibuya over [multipass](https://multipass.run/) and [orbstack](https://orbstack.dev/) (tho its' paid, tho...) both are VM based solution to use docker engine, both has treated guest os as arm64 based. thats the reason. but I will try Colima.

as for port-forwarding, multipass and orbstack has assigned private ip address to vm so I confirm shibuya UI over http://192.168.64.29:8080/  (multipass has used subnet 192.168.64.*)

**Comment by iandyh** [comment]
@rsw-a yeah, looking at your answer, I guess it's due to the different container runtime we are using locally. If colima works for you, I can update the README to require the developer to use Colima. Otherwise providing support for different runtime could be very challenging...

**Comment by muthuv1** [comment]
I am able to run shibuya on local with multipass VM and kind in it, with this change.

Also as mentioned by Kimura-san regarding DB image, the issue is below
**Does not have arm64 image**: https://hub.docker.com/_/mariadb/tags?page=&page_size=&ordering=&name=10.0.23
**Have arm64 image from this version**: https://hub.docker.com/_/mariadb/tags?page=&page_size=&ordering=&name=10.0.36

So version "image: mariadb:10.0.36" works in arm64 VM in local [file: kubernetes/db.yaml].

**Review by muthuv1 — APPROVED** [review]
LGTM

**Review by muthuv1 — APPROVED** [review]

**Pull request merged**
