### PR TITLE
switch from docker.io to gcr.io for building images

### PR DESCRIPTION
**Pull request by harpratap**
Hitting the docker pull limits when building from local and CI/CD, so switching to gcr instead

### CODE REVIEW

**Comment by iandyh** [comment]
This is using shibuya GCP project. So are these images public?

**Comment by harpratap** [comment]
@iandyh Yes. There's no free tier for gcr.io so need to add to our own project

**Comment by iandyh** [comment]
@harpratap I think you commit with your internal id. You might want to rebase.

**Comment by harpratap** [comment]
@iandyh Thanks for that, updated now

**Pull request merged**
